//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
//+
// Provider PwnedPassword Event Count 10
//+
EXTERN_C __declspec(selectany) const GUID PWNED_GUID = {0x60069ff2, 0xa00b, 0x49ae, {0xa8, 0xc3, 0x51, 0xb0, 0x75, 0xce, 0xe1, 0x81}};

//
// Channel
//
#define FILE_CHANNEL 0x10
#define PWNED_GUID_CHANNEL_System 0x8

//
// Opcodes
//
#define INIT_OP 0xa
#define READ_OP 0xc
#define ENCODE_OP 0xd
#define SEND_OP 0xe
#define RECEIVE_OP 0xf

//
// Tasks
//
#define NETWORK_TASK 0x1
#define OS_TASK 0x2
#define REG_TASK 0x3
#define VALIDATE_TASK 0x4

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_INITATED = {0x64, 0x0, 0x8, 0x4, 0xa, 0x2, 0x4000000000000000};
#define EVT_INITATED_value 0x64
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_ACTIVATED = {0x66, 0x0, 0x8, 0x4, 0xa, 0x2, 0x4000000000000000};
#define EVT_ACTIVATED_value 0x66
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_REGREAD_TRUE = {0xc8, 0x0, 0x8, 0x4, 0xc, 0x3, 0x4000000000000000};
#define EVT_REGREAD_TRUE_value 0xc8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_REGREAD_FALSE = {0xc9, 0x0, 0x8, 0x3, 0xc, 0x3, 0x4000000000000000};
#define EVT_REGREAD_FALSE_value 0xc9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_DWREGREAD_TRUE = {0xca, 0x0, 0x8, 0x4, 0xc, 0x3, 0x4000000000000000};
#define EVT_DWREGREAD_TRUE_value 0xca
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_DWREGREAD_FALSE = {0x0, 0x0, 0x8, 0x3, 0xc, 0x3, 0x4000000000000000};
#define EVT_DWREGREAD_FALSE_value 0x0
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_SHOWHANDLE = {0x12c, 0x0, 0x8, 0x4, 0xa, 0x1, 0x4000000000000000};
#define EVT_SHOWHANDLE_value 0x12c
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_WARNGENERIC = {0x3e8, 0x0, 0x8, 0x3, 0x0, 0x0, 0x4000000000000000};
#define EVT_WARNGENERIC_value 0x3e8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_PASSWORD_ACCEPTED = {0x190, 0x0, 0x8, 0x3, 0xf, 0x4, 0x4020000000000000};
#define EVT_PASSWORD_ACCEPTED_value 0x190
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_PASSWORD_REJECTED = {0x191, 0x0, 0x8, 0x2, 0xf, 0x4, 0x4010000000000000};
#define EVT_PASSWORD_REJECTED_value 0x191
#define MSG_PwnedPassword_event_0_message    0x00000000L
#define MSG_PwnedPassword_event_100_message  0x00000064L
#define MSG_PwnedPassword_event_101_message  0x00000066L
#define MSG_PwnedPassword_event_200_message  0x000000C8L
#define MSG_PwnedPassword_event_111_message  0x000000C9L
#define MSG_PwnedPassword_event_202_message  0x000000CAL
#define MSG_PwnedPassword_event_300_message  0x0000012CL
#define MSG_PwnedPassword_event_400_message  0x00000190L
#define MSG_PwnedPassword_event_401_message  0x00000191L
#define MSG_PwnedPassword_event_1000_message 0x000003E8L
#define MSG_keyword_AuditFailure             0x10000035L
#define MSG_keyword_AuditSuccess             0x10000036L
#define MSG_level_Error                      0x50000002L
#define MSG_level_Warning                    0x50000003L
#define MSG_level_Informational              0x50000004L
#define MSG_task_None                        0x70000000L
#define MSG_PwnedPassword_channel_DEBUG_FILE_message 0x90000001L
#define MSG_channel_System                   0x90000002L
